### PR TITLE
Upgrade Timex to support newer versions of Elixir

### LINKED ISSUE #2: Unable to compile on Elixir 1.3.2
From what I can tell, this is fixed in the newest version of Timex.

```
== Compilation error on file lib/date/date_format.ex ==
** (ArgumentError) defdelegate/2 only accepts function parameters, got: %DateTime{} = date
    (elixir) lib/kernel/utils.ex:55: Kernel.Utils.add_arg/2
    (elixir) lib/kernel/utils.ex:25: Kernel.Utils.defdelegate/2
    lib/date/date_format.ex:22: anonymous fn/3 in :elixir_compiler_3.__MODULE__/1
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/date/date_format.ex:22: (module)

could not compile dependency :timex, "mix compile" failed. You can recompile this dependency with "mix deps.compile timex", update it with "mix deps.update timex" or clean it with "mix deps.clean timex"
```

### PR DESCRIPTION
**Pull request by davishmcclurg**
Fixes #2

### CODE REVIEW

**Comment by umurgdk** [comment]
@davishmcclurg can you please update the `.travis.yml` file to use correct elixir version (please check travis build errors on this PR)

**Comment by davishmcclurg** [comment]
@umurgdk I updated `.travis.yml` and the build is green.
